spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/gb_shop
    username: postgres
    password: password
  flyway:
    baseline-on-migrate: true